#!/bin/bash
# Builds the Mac app: the same SwiftUI sources as the iPhone app, compiled for
# macOS, with the emulator library and every Homebrew library it needs copied
# inside the bundle, so the result runs on a Mac that has no Homebrew.
#
# The emulator is the macOS build of the same fork (-Dshared_lib=true,
# -Dhvf=enabled), found in ../build/inferno-macos or ~/inferno-ios/build/
# inferno-macos, or wherever INFERNO_MAC_DYLIB points.
#
# The app lands in app/.build-mac/Inferno.app, and a zip of it and a disk image
# to install it from in the project root beside Inferno.ipa, where builds are
# picked up by hand.
set -euo pipefail

# A library path from the shell's profile (DYLD_LIBRARY_PATH=/opt/homebrew/lib is
# a common one) reaches actool's ibtoold, and on a case-insensitive disk
# Homebrew's libpng.dylib then stands in for ImageIO's own libPng.dylib: ibtoold
# dies with a bus error reading the first PNG and actool exits 255 without a
# word. Nothing here needs such a path.
unset DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH

ROOT="$(cd "$(dirname "$0")" && pwd)"
PROJECT="$(cd "$ROOT/.." && pwd)"
BUILD="$ROOT/.build-mac"
APP="$BUILD/Inferno.app"
ZIP="$PROJECT/Inferno-macOS.zip"
DMG="$PROJECT/Inferno-macOS.dmg"
SDK="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="arm64-apple-macos15.0"

DYLIB="${INFERNO_MAC_DYLIB:-}"
if [ -z "$DYLIB" ]; then
    for candidate in \
        "$ROOT/../build/inferno-macos/libqemu-aarch64-softmmu.dylib" \
        "$HOME/inferno-ios/build/inferno-macos/libqemu-aarch64-softmmu.dylib"
    do
        [ -f "$candidate" ] && DYLIB="$candidate" && break
    done
fi
[ -n "$DYLIB" ] && [ -f "$DYLIB" ] || {
    echo "No macOS emulator library. Build it (see the header) or set INFERNO_MAC_DYLIB=" >&2
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Frameworks" "$APP/Contents/Resources"

echo "==> Compiling"
# A stamp in the log removes any doubt about which build is actually running.
STAMP="$(date '+%Y-%m-%d %H:%M:%S')"
cat > "$ROOT/Sources/BuildInfo.swift" <<EOF
// Generated by build-mac.sh — do not edit.
enum BuildInfo {
    static let stamp = "$STAMP"
}
EOF
xcrun --sdk macosx swiftc \
    -target "$TARGET" \
    -sdk "$SDK" \
    -O -wmo \
    -parse-as-library \
    -Xlinker -rpath -Xlinker @executable_path/../Frameworks \
    -o "$APP/Contents/MacOS/Inferno" \
    "$ROOT"/Sources/*.swift

echo "==> Bundle"
cp "$ROOT/Resources/Info-macOS.plist" "$APP/Contents/Info.plist"
cp "$DYLIB" "$APP/Contents/Frameworks/"
# What a restore seeds the small SEP-state disks from — see RestorePrep.swift.
cp -R "$ROOT/Resources/SEPTemplates" "$APP/Contents/Resources/SEPTemplates"

# Every non-system library the emulator reaches, copied beside it and relinked
# to be found there. Homebrew's own paths are absolute and would tie the app to
# this Mac; walked until nothing new turns up, since glib brings its own.
echo "==> Libraries"
FRAMEWORKS="$APP/Contents/Frameworks"
foreign() { otool -L "$1" | tail -n +2 | awk '{print $1}' | grep -E '^/(opt/homebrew|usr/local)/' || true; }
queue=("$FRAMEWORKS/$(basename "$DYLIB")")
while [ ${#queue[@]} -gt 0 ]; do
    lib="${queue[0]}"; queue=("${queue[@]:1}")
    chmod u+w "$lib"
    install_name_tool -id "@rpath/$(basename "$lib")" "$lib" 2>/dev/null
    install_name_tool -add_rpath @loader_path "$lib" 2>/dev/null || true
    for dep in $(foreign "$lib"); do
        name="$(basename "$dep")"
        if [ ! -f "$FRAMEWORKS/$name" ]; then
            cp "$(realpath "$dep")" "$FRAMEWORKS/$name"
            queue+=("$FRAMEWORKS/$name")
        fi
        install_name_tool -change "$dep" "@rpath/$name" "$lib" 2>/dev/null
    done
done
leftover="$(for lib in "$FRAMEWORKS"/*.dylib; do foreign "$lib"; done | sort -u)"
[ -z "$leftover" ] || { echo "Still pointing outside the bundle:" >&2; echo "$leftover" >&2; exit 1; }
echo "    $(ls "$FRAMEWORKS" | wc -l | tr -d ' ') libraries"

# QEMU's data directory. The VNC server refuses to start without keymaps, and
# Inferno drops them from its tree, so take them from a stock QEMU.
KEYMAPS="${INFERNO_KEYMAPS:-/opt/homebrew/share/qemu/keymaps}"
[ -d "$KEYMAPS" ] || { echo "No keymap files: $KEYMAPS" >&2; exit 1; }
mkdir -p "$APP/Contents/Resources/qemu-data"
cp -R "$KEYMAPS" "$APP/Contents/Resources/qemu-data/keymaps"

# The app icon, from the same Icon Composer bundle the iPhone app uses.
ICON="$ROOT/Resources/Inferno.icon"
if [ -z "${INFERNO_NO_ICON:-}" ] && [ -d "$ICON" ]; then
    echo "==> Icon"
    xcrun actool --compile "$APP/Contents/Resources" \
        --platform macosx \
        --minimum-deployment-target 15.0 \
        --app-icon Inferno \
        --output-partial-info-plist "$BUILD/icon.plist" \
        "$ICON" > /dev/null
    python3 - "$APP/Contents/Info.plist" "$BUILD/icon.plist" <<'PY'
import plistlib, sys
target, partial = sys.argv[1], sys.argv[2]
with open(target, 'rb') as f: info = plistlib.load(f)
with open(partial, 'rb') as f: extra = plistlib.load(f)
extra.pop('com.apple.actool.compilation-results', None)
info.update(extra)
with open(target, 'wb') as f: plistlib.dump(info, f)
PY
fi

# The programs the app carries into the guest. They are iOS binaries for the
# guest, not for the Mac, so they are the same ones the iPhone app bundles.
if [ -z "${INFERNO_NO_NSIO:-}" ] && command -v ldid >/dev/null 2>&1; then
    echo "==> Guest tools"
    TOOLS="$APP/Contents/Resources/guest-tools"
    mkdir -p "$TOOLS"
    "$ROOT/../netlab/build-nsio.sh" "$TOOLS/nsio" >/dev/null
    "$ROOT/../netlab/build-sbnet.sh" "$BUILD/sbnet" >/dev/null
    gzip -9 -n -c "$BUILD/sbnet" > "$TOOLS/sbnet.gz"
    "$ROOT/../netlab/build-agent.sh" "$BUILD/agent" >/dev/null
    gzip -9 -n -c "$BUILD/agent" > "$TOOLS/agent.gz"
else
    echo "    no ldid — building without the guest tools (no fast channel, no agent, no status bar)"
fi

echo "==> Signing"
# Ad-hoc unless told otherwise, which is what a release ships. To macOS's privacy
# checks every ad-hoc rebuild is a new app, so each one asks again for the
# Documents folder and hangs at launch until someone answers. INFERNO_MAC_SIGN
# names a certificate to sign with instead, and the same certificate keeps the
# answer from one build to the next.
SIGN="${INFERNO_MAC_SIGN:--}"
# Inside out: the libraries first, since the app's seal covers them.
for lib in "$FRAMEWORKS"/*.dylib; do
    codesign --force --sign "$SIGN" --timestamp=none "$lib"
done
codesign --force --sign "$SIGN" --timestamp=none \
    --entitlements "$ROOT/Resources/entitlements-macos.plist" \
    "$APP"

echo "==> Packaging"
rm -f "$ZIP"
ditto -c -k --keepParent "$APP" "$ZIP"

# The disk image a release offers: the app beside a link to Applications, to be
# dragged across. Made from a folder holding only those two, so nothing else
# from the build directory ends up in it.
STAGE="$BUILD/dmg"
rm -rf "$STAGE" "$DMG"
mkdir -p "$STAGE"
ditto "$APP" "$STAGE/Inferno.app"
ln -s /Applications "$STAGE/Applications"
hdiutil create -volname Inferno -srcfolder "$STAGE" -format UDZO -ov "$DMG" >/dev/null
rm -rf "$STAGE"

echo
echo "Done: $APP"
echo "      $ZIP"
echo "      $DMG"
ls -lh "$ZIP" "$DMG"
